---
- name: Setting autologon for vagrant user
  community.windows.win_auto_logon:
    username: vagrant
    password: vagrant

- name: Setting exececution policy to "Unrestricted"
  ansible.windows.win_shell: Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine -Force

- name: Unhiding protected OS files
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: ShowSuperHidden
    data: 1
    type: dword

- name: Unhiding file extensions
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: HideFileExt
    data: 0
    type: dword

- name: Unhiding hidden files
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: Hidden
    data: 1
    type: dword

- name: Disabling Bing search
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Search
    name: BingSearchEnabled
    data: 0
    type: dword

- name: Disabling Game Bar Tips
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\GameBar
    name: ShowStartupPanel
    data: 0
    type: dword

- name: Disabling System Restore
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\SystemRestore
    name: DisableSR
    data: 1
    type: dword

- name: Disabling UAC
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: EnableLUA
    data: 0
    type: dword

- name: Ensuring SSH server is disabled
  ansible.windows.win_service:
    name: sshd
    state: absent

- name: Removing BgInfo
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run
    name: bginfo
    state: absent

- name: Disabling Windows Updates
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: NoAutoUpdate
    data: 1
    type: dword

- name: Disabling firewall
  community.windows.win_firewall:
    state: disabled
    profiles:
      - Domain
      - Private
      - Public

- name: Disabling Defender real-time protection
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection
    name: DisableRealtimeMonitoring
    data: 1
    type: dword

- name: Disabling Defender cloud-delivered protection
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Spynet
    name: SpynetReporting
    data: 0
    type: dword

- name: Disabling Defender automatic sample submission
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Spynet
    name: SubmitSamplesConsent
    data: 2
    type: dword

- name: Setting %SYSTEMDRIVE% fact
  set_fact:
    system_drive: C:\

- name: Adding the directory C:\ to the exclusion list
  ansible.windows.win_shell: Add-MpPreference -ExclusionPath {{ system_drive }} -Force

- name: Disabling Action Center
  ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer
    name: HideSCAHealth
    data: 1
    type: dword

- name: Setting Windows Aero theme
  ansible.windows.win_regedit:
    path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ThemeManager
    name: DllName
    data: C:\Windows\resources\themes\Aero\Aero.msstyles
    type: expandstring

- name: Setting Windows Aero theme
  ansible.windows.win_regedit:
    path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ThemeManager
    name: ThemeActive
    data: 1
    type: string

- name: Setting Windows Aero theme
  ansible.windows.win_regedit:
    path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes
    name: CurrentTheme
    data: C:\Windows\resources\Themes\aero.theme
    type: string

- name: Downloading SentinelLabs wallpaper
  ansible.windows.win_get_url:
    url: https://raw.githubusercontent.com/SentineLabs/SentinelLabs_RevCore_Tools/master/Logo_Wallpaper_Desktop_1920x1080.png
    dest: C:\Users\Public\Pictures\101089633-48da3e80-356a-11eb-9d66-0cdf9da30220.png

- name: Setting wallpaper
  ansible.windows.win_regedit:
    path: HKCU:\Control Panel\Desktop
    name: Wallpaper
    data: C:\Users\Public\Pictures\101089633-48da3e80-356a-11eb-9d66-0cdf9da30220.png
    type: string

- name: Setting wallpaper
  ansible.windows.win_regedit:
    path: HKCU:\Control Panel\Desktop
    name: WallpaperStyle
    data: 0
    type: dword

- name: Setting wallpaper
  ansible.windows.win_regedit:
    path: HKCU:\Control Panel\Desktop
    name: StretchWallpaper
    data: 2
    type: dword

- name: Setting wallpaper
  ansible.windows.win_regedit:
    path: HKCU:\Control Panel\Colors
    name: Background
    data: 0 0 0
    type: string

- name: Installing SentinelLabs RevCore Tools
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item }}"
    state: latest
  with_items: "{{ revcore_tools }}"

- name: Refreshing environment to reflect changes
  ansible.windows.win_shell: refreshenv

- name: Downloading get-pip.py
  ansible.windows.win_get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: C:\Windows\Temp\get-pip.py

- name: Installing Pip
  ansible.windows.win_shell: python get-pip.py
  args:
    chdir: C:\Windows\Temp

- name: Removing get-pip.py
  ansible.windows.win_file:
    path: C:\Windows\Temp\get-pip.py
    state: absent

- name: Upgrading setuptools
  ansible.windows.win_shell: python -m pip install --upgrade setuptools

- name: Installing Python packages
  ansible.windows.win_shell: python -m pip install pefile yara

- name: Creating x64dbg desktop shortcut
  community.windows.win_shortcut:
    src: C:\ProgramData\chocolatey\lib\x64dbg.portable\tools\release\x64\x64dbg.exe
    dest: C:\Users\Public\Desktop\x64dbg.lnk

- name: Creating x32dbg desktop shortcut
  community.windows.win_shortcut:
    src: C:\ProgramData\chocolatey\lib\x64dbg.portable\tools\release\x32\x32dbg.exe
    dest: C:\Users\Public\Desktop\x32dbg.lnk

- name: Creating OLLYDBG desktop shortcut
  community.windows.win_shortcut:
    src: C:\Program Files (x86)\OllyDbg\OLLYDBG.EXE
    dest: C:\Users\Public\Desktop\OLLYDBG.lnk

- name: Creating HXD desktop shortcut
  community.windows.win_shortcut:
    src: C:\Program Files\HxD\HxD.exe
    dest: C:\Users\Public\Desktop\HxD.lnk

- name: Creating PEbear desktop shortcut
  community.windows.win_shortcut:
    src: C:\ProgramData\chocolatey\lib\pebear\tools\PE-bear.exe
    dest: C:\Users\Public\Desktop\PEbear.lnk

- name: Creating pestudio desktop shortcut
  community.windows.win_shortcut:
    src: C:\ProgramData\chocolatey\lib\PeStudio\tools\pestudio\pestudio.exe
    dest: C:\Users\Public\Desktop\pestudio.lnk

- name: Creating procexp desktop shortcut
  community.windows.win_shortcut:
    src: C:\ProgramData\chocolatey\lib\procexp\tools\procexp.exe
    dest: C:\Users\Public\Desktop\proexp.lnk

- name: Creating Autoruns desktop shortcut
  community.windows.win_shortcut:
    src: C:\ProgramData\chocolatey\lib\AutoRuns\tools\Autoruns.exe
    dest: C:\Users\Public\Desktop\Autoruns.lnk

- name: Creating Sysmon desktop shortcut
  community.windows.win_shortcut:
    src: C:\ProgramData\chocolatey\lib\sysmon\tools\Sysmon.exe
    dest: C:\Users\Public\Desktop\Sysmon.lnk

- name: Creating Tcpview desktop shortcut
  community.windows.win_shortcut:
    src: C:\ProgramData\chocolatey\lib\TcpView\Tools\Tcpview.exe
    dest: C:\Users\Public\Desktop\Tcpview.lnk

- name: Creating notepad++ desktop shortcut
  community.windows.win_shortcut:
    src: C:\Program Files\Notepad++\notepad++.exe
    dest: C:\Users\Public\Desktop\notepad++.lnk

- name: Creating Cmder desktop shortcut
  community.windows.win_shortcut:
    src: C:\tools\Cmder\Cmder.exe
    dest: C:\Users\Public\Desktop\Cmder.lnk

- name: Setting internal network gateway for inetsim routing
  ansible.windows.win_shell: Remove-NetIPAddress 192.168.56.103 -Confirm:$false

- name: Setting internal network gateway for inetsim routing
  ansible.windows.win_shell: New-NetIPAddress -InterfaceAlias 'Ethernet 2' -IPAddress '192.168.56.103' -PrefixLength 24 -DefaultGateway '192.168.56.102'

- name: Setting DNS for inetsim routing
  ansible.windows.win_dns_client:
    adapter_names: 'Ethernet 2'
    dns_servers: 192.168.56.102

- name: Rebooting machine to make changes take effect
  ansible.windows.win_reboot:
